build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

app_name: demo # don't change
jar_name: DStashek-demo # set this to '<first_initial><lastname>-demo' ex: sgreenberg-demo

github_app_repo_uri: https://github.com/Dstashek/demo-initial.git # https url of your demo app github fork.  ex: https://github.com/spgreenberg/demo-initial.git
github_app_repo_branch: master # don't change

github_pipelines_repo_uri: https://github.com/Dstashek/training-pipelines-initial.git # https url of your training-pipelines-initial fork.  ex: https://github.com/spgreenberg/training-pipelines-initial.git
github_pipelines_repo_branch: master # don't change

version_bucket: rscale-training-bucket # don't change
version_bucket_region_name: us-west-2 # don't change

version_key: DStashek-demo-0.0.1 # set to '<first_initial><lastname>-demo-version'.  ex: sgreenberg-demo-version
initial_version: 0.0.1

artifact_regexp: DStashek-demo-(.*).jar # set to '<first_initial><lastname>-demo-(.*).jar'.  ex: sgreenberg-demo-(.*).jar
artifact_bucket: rscale-training-bucket # don't change
artifact_bucket_region_name: us-west-2 # don't change

cf_dev_api: https://api.run.pivotal.io # set to cf api endpoint
cf_dev_organization: rscale-training-3 # set to your org
cf_dev_space: daniel.stashek@cgi.com # set to your space
cf_dev_hostname: demo-DStashek # set to 'demo-<first_initial><lastname>'. ex: demo-sgreenberg
cf_dev_domain: cfapps.io # set to the apps domain for your CF
cf_dev_manifest: demo_manifest.yml # set to the dev manifest path in your demo app repository. ex: dev-manifest.yml
